In [1]:
import torch
from torch import nn

In [2]:
net = nn.Sequential(nn.Linear(4, 8), nn.ReLU(), nn.Linear(8, 1))
X = torch.rand(size=(2, 4))
net(X)

tensor([[-0.0560],
        [-0.1229]], grad_fn=<AddmmBackward0>)

### 1. 参数访问

In [3]:
print(net[2].state_dict())

OrderedDict([('weight', tensor([[ 0.1091, -0.2863,  0.2871, -0.1166, -0.2729, -0.0951,  0.3049,  0.0003]])), ('bias', tensor([-0.1973]))])


PyTorch中每个参数都是参数类的一个实例，参数是一个复合对象，包含**值，梯度和一些其他信息**

In [4]:
print(type(net[2].bias))
print(net[2].bias)
print(net[2].bias.data)

<class 'torch.nn.parameter.Parameter'>
Parameter containing:
tensor([-0.1973], requires_grad=True)
tensor([-0.1973])
